# lab.clj.polymer

A laboratory for experimenting with Google Polymer and Clojure/ClojureScript

* <<start,getting started>>
* <<html,html: a purely functional language>>


= [[start]] getting started

Working with link:https://www.polymer-project.org/1.0/[Polymer]
directly involves:

* writing "web source code", a combination of
** HTML
** javascript
*** Events
*** etc.
** CSS
*** link:doc/Styling.adoc[Styling]
*** link:doc/Laout.adoc[Layout]
* partitioning logic across server and client

The tricky bit is coordinating the URIs in the HTML that will end up
being GETted, and the "routes" that handle them on the server side.
One design goal of Miraj is to eliminate this anoyance.


Polymer is based on standard
link:http://www.w3.org/standards/techs/components#w3c_all[Web
Components]

See also

* link:http://www.2ality.com/2015/08/web-component-status.html[What
happened to web components?]

* link:https://hacks.mozilla.org/2015/06/the-state-of-web-components/[The State of Web Components] (9 June 2015): "Web Components have been in planning for over three years, but we’re optimistic the end is near. All major vendors are on board, enthusiastic, and investing significant time to help resolve the remaining issues."



= [[html]] HTML as a purely functional language

== JSVM configuration

The `<head>` element in an html file essentially configures the JSVM
(Javascript Virtual Machine):

* `<meta>` elements set the metadata of the JSVM

* `<script>` elements prepare the JSVM runtime environment by
  pre-registering the functions and variables that will be used by the page

* `<style>` elements register the stylesheet for the page

The `<script>` element is analogous to Clojure's `require` function.

In a standard Javascript environment, we have no namespaces, so
everything is organized by file.  This means you have to keep track of
which files are needed and write a `<script>` declaration for each one.

With Clojure and Clojurescript we have namespaces, so we don't worry
about files.  We `require` namespaces, and the runtime is responsible
for translating them into file names, finding the files, and loading
them.  We can do the same thing for loading Javascript files into the
browser: require a namespace, and let the Clojure runtime figure out
and write the `<script>` expressions.

So we're going to use Clojure to hide the complexity of the html
`<head>` element.  Instead of

[source,html]
----
<html>
  <head>
    <script src="foo/bar.html"></script>
...
----

we will write something like

[source,clojure]
----
(html-ns
  (:require [foo.bar]))
...
----

The HTML content of the page is just Clojure code.  Similar to Hiccup,
but without any specialized syntax: if you need a `foo` element you
write `(foo ...)` rather than `[:foo ...]`.

Compare:

[source,clojre]
----
(ns foo.bar)
(println "Hello world!")
----

and

[source,html]
----
<html>
  <body>
  Hello world.
  </body>
</html>
----

This directly translates, both conceptually and formally.  Just map
`<html>` to `(ns foo.bar)`, and treat `<body>` as a function:

[source,clojure]
----
(ns html)
(body "Hello world!")
----


== code organization

* Use a jar for the Polymer library. Either roll your own or use `miraj`.

